begin;

create extension if not exists pgcrypto;

create table if not exists public.tg_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tg_telegram_status (
  user_id uuid primary key references auth.users(id) on delete cascade,
  status text not null default 'not_configured'
    check (status in ('not_configured','code_sent','2fa_required','connected','error','disconnected')),
  phone_hint text,
  last_error text,
  updated_at timestamptz not null default now()
);

create table if not exists public.tg_telegram_private (
  user_id uuid primary key references auth.users(id) on delete cascade,
  api_id bigint not null,
  api_hash_enc text not null,
  phone_enc text not null,
  pending_session_enc text,
  session_enc text,
  phone_code_hash_enc text,
  updated_at timestamptz not null default now()
);

create table if not exists public.tg_alert_settings (
  user_id uuid primary key default auth.uid() references auth.users(id) on delete cascade,
  provider text not null default 'ntfy'
    check (provider in ('ntfy','none')),
  ntfy_topic text not null default ('promo-' || replace(gen_random_uuid()::text,'-','')),
  ntfy_priority smallint not null default 5
    check (ntfy_priority between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tg_keywords (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  word text not null check (length(btrim(word)) between 1 and 180),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists tg_keywords_user_word_ci_uq
  on public.tg_keywords(user_id, lower(btrim(word)));

create table if not exists public.tg_groups (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  telegram_group_id bigint not null,
  name text not null default '',
  username text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, telegram_group_id)
);

create table if not exists public.tg_group_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  identifier text not null check (length(btrim(identifier)) between 1 and 180),
  status text not null default 'pending'
    check (status in ('pending','processing','resolved','error')),
  error_message text,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);
create index if not exists tg_group_requests_pending_idx
  on public.tg_group_requests(user_id, status, id);

create table if not exists public.tg_occurrences (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  occurred_at timestamptz not null default now(),
  telegram_date timestamptz,
  telegram_group_id bigint,
  group_name text not null default '',
  username text not null default '',
  sender text not null default '',
  keyword text not null default '',
  message text not null default '',
  message_id bigint,
  message_link text not null default '',
  is_coupon boolean not null default false,
  created_at timestamptz not null default now()
);
create unique index if not exists tg_occurrences_message_uq
  on public.tg_occurrences(user_id, telegram_group_id, message_id, keyword);
create index if not exists tg_occurrences_user_date_idx
  on public.tg_occurrences(user_id, occurred_at desc);

create table if not exists public.tg_coupon_sites (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  store_name text not null check (length(btrim(store_name)) between 1 and 120),
  store_slug text not null check (length(btrim(store_slug)) between 1 and 160),
  sources text[] not null default array['meliuz','cuponeria','picodi','promobit']::text[],
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists tg_coupon_sites_user_slug_uq
  on public.tg_coupon_sites(user_id, lower(btrim(store_slug)));

create table if not exists public.tg_coupons (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  coupon_key text not null,
  source text not null check (source in ('telegram','meliuz','cuponeria','picodi','promobit','manual')),
  store_name text not null default '',
  title text not null default '',
  code text,
  discount_text text,
  details text,
  source_url text,
  source_group text,
  active boolean not null default true,
  discovered_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  expires_at timestamptz,
  unique(user_id, coupon_key)
);
create index if not exists tg_coupons_user_seen_idx
  on public.tg_coupons(user_id, last_seen_at desc);

create table if not exists public.tg_worker_status (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state text not null default 'offline',
  last_heartbeat timestamptz,
  groups_active integer not null default 0,
  keywords_active integer not null default 0,
  last_error text,
  version text,
  updated_at timestamptz not null default now()
);

create or replace function public.tg_set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists tg_profiles_updated_at on public.tg_profiles;
create trigger tg_profiles_updated_at before update on public.tg_profiles
for each row execute function public.tg_set_updated_at();

drop trigger if exists tg_alert_settings_updated_at on public.tg_alert_settings;
create trigger tg_alert_settings_updated_at before update on public.tg_alert_settings
for each row execute function public.tg_set_updated_at();

drop trigger if exists tg_keywords_updated_at on public.tg_keywords;
create trigger tg_keywords_updated_at before update on public.tg_keywords
for each row execute function public.tg_set_updated_at();

drop trigger if exists tg_groups_updated_at on public.tg_groups;
create trigger tg_groups_updated_at before update on public.tg_groups
for each row execute function public.tg_set_updated_at();

drop trigger if exists tg_coupon_sites_updated_at on public.tg_coupon_sites;
create trigger tg_coupon_sites_updated_at before update on public.tg_coupon_sites
for each row execute function public.tg_set_updated_at();

create or replace function public.tg_on_auth_user_created()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.tg_profiles(user_id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name',''))
  on conflict (user_id) do nothing;

  insert into public.tg_telegram_status(user_id,status)
  values (new.id,'not_configured')
  on conflict (user_id) do nothing;

  insert into public.tg_worker_status(user_id,state)
  values (new.id,'offline')
  on conflict (user_id) do nothing;

  insert into public.tg_alert_settings(user_id)
  values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists tg_auth_user_created on auth.users;
create trigger tg_auth_user_created after insert on auth.users
for each row execute function public.tg_on_auth_user_created();

insert into public.tg_profiles(user_id) select id from auth.users on conflict do nothing;
insert into public.tg_telegram_status(user_id,status) select id,'not_configured' from auth.users on conflict do nothing;
insert into public.tg_worker_status(user_id,state) select id,'offline' from auth.users on conflict do nothing;
insert into public.tg_alert_settings(user_id) select id from auth.users on conflict do nothing;

create or replace function public.tg_cleanup_old_data()
returns void language plpgsql security definer set search_path = public as $$
begin
  delete from public.tg_occurrences
  where occurred_at < now() - interval '24 hours';

  delete from public.tg_coupons
  where last_seen_at < now() - interval '48 hours';
end;
$$;

create extension if not exists pg_cron;
do $$
declare v_job bigint;
begin
  for v_job in select jobid from cron.job where jobname='tg-cleanup-old-data'
  loop perform cron.unschedule(v_job); end loop;

  perform cron.schedule(
    'tg-cleanup-old-data',
    '15 * * * *',
    'select public.tg_cleanup_old_data();'
  );
exception when others then
  raise notice 'pg_cron não pôde ser agendado: %', sqlerrm;
end $$;

alter table public.tg_profiles enable row level security;
alter table public.tg_telegram_status enable row level security;
alter table public.tg_telegram_private enable row level security;
alter table public.tg_alert_settings enable row level security;
alter table public.tg_keywords enable row level security;
alter table public.tg_groups enable row level security;
alter table public.tg_group_requests enable row level security;
alter table public.tg_occurrences enable row level security;
alter table public.tg_coupon_sites enable row level security;
alter table public.tg_coupons enable row level security;
alter table public.tg_worker_status enable row level security;

revoke all on public.tg_telegram_private from anon, authenticated;
revoke all on public.tg_profiles, public.tg_telegram_status, public.tg_alert_settings, public.tg_keywords,
  public.tg_groups, public.tg_group_requests, public.tg_occurrences,
  public.tg_coupon_sites, public.tg_coupons, public.tg_worker_status from anon;

grant select, update on public.tg_profiles to authenticated;
grant select on public.tg_telegram_status to authenticated;
grant select, insert, update on public.tg_alert_settings to authenticated;
grant select, insert, update, delete on public.tg_keywords to authenticated;
grant select, insert, update, delete on public.tg_groups to authenticated;
grant select, insert, update, delete on public.tg_group_requests to authenticated;
grant select on public.tg_occurrences to authenticated;
grant select, insert, update, delete on public.tg_coupon_sites to authenticated;
grant select on public.tg_coupons to authenticated;
grant select on public.tg_worker_status to authenticated;

grant usage, select on sequence public.tg_keywords_id_seq to authenticated;
grant usage, select on sequence public.tg_groups_id_seq to authenticated;
grant usage, select on sequence public.tg_group_requests_id_seq to authenticated;
grant usage, select on sequence public.tg_coupon_sites_id_seq to authenticated;

create policy "profile_select_own" on public.tg_profiles
for select to authenticated using (user_id=auth.uid());
create policy "profile_update_own" on public.tg_profiles
for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());

create policy "telegram_status_select_own" on public.tg_telegram_status
for select to authenticated using (user_id=auth.uid());
create policy "worker_status_select_own" on public.tg_worker_status
for select to authenticated using (user_id=auth.uid());

create policy "alert_settings_select_own" on public.tg_alert_settings
for select to authenticated using (user_id=auth.uid());
create policy "alert_settings_insert_own" on public.tg_alert_settings
for insert to authenticated with check (user_id=auth.uid());
create policy "alert_settings_update_own" on public.tg_alert_settings
for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());

create policy "keywords_select_own" on public.tg_keywords for select to authenticated using (user_id=auth.uid());
create policy "keywords_insert_own" on public.tg_keywords for insert to authenticated with check (user_id=auth.uid());
create policy "keywords_update_own" on public.tg_keywords for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "keywords_delete_own" on public.tg_keywords for delete to authenticated using (user_id=auth.uid());

create policy "groups_select_own" on public.tg_groups for select to authenticated using (user_id=auth.uid());
create policy "groups_insert_own" on public.tg_groups for insert to authenticated with check (user_id=auth.uid());
create policy "groups_update_own" on public.tg_groups for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "groups_delete_own" on public.tg_groups for delete to authenticated using (user_id=auth.uid());

create policy "group_requests_select_own" on public.tg_group_requests for select to authenticated using (user_id=auth.uid());
create policy "group_requests_insert_own" on public.tg_group_requests for insert to authenticated with check (user_id=auth.uid());
create policy "group_requests_delete_own" on public.tg_group_requests for delete to authenticated using (user_id=auth.uid());

create policy "occurrences_select_own" on public.tg_occurrences for select to authenticated using (user_id=auth.uid());

create policy "coupon_sites_select_own" on public.tg_coupon_sites for select to authenticated using (user_id=auth.uid());
create policy "coupon_sites_insert_own" on public.tg_coupon_sites for insert to authenticated with check (user_id=auth.uid());
create policy "coupon_sites_update_own" on public.tg_coupon_sites for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "coupon_sites_delete_own" on public.tg_coupon_sites for delete to authenticated using (user_id=auth.uid());

create policy "coupons_select_own" on public.tg_coupons for select to authenticated using (user_id=auth.uid());

commit;
