-- UPGRADE V1 -> V2 MULTIUSUÁRIO
-- Faça backup antes.
-- Troque REPLACE_WITH_OWNER_UUID pelo UUID do seu usuário atual.

begin;


-- Remove as policies administrativas da V1 antes de ativar isolamento por usuário.
drop policy if exists "tg_keywords_admin_select" on public.tg_keywords;
drop policy if exists "tg_keywords_admin_insert" on public.tg_keywords;
drop policy if exists "tg_keywords_admin_update" on public.tg_keywords;
drop policy if exists "tg_keywords_admin_delete" on public.tg_keywords;

drop policy if exists "tg_groups_admin_select" on public.tg_groups;
drop policy if exists "tg_groups_admin_insert" on public.tg_groups;
drop policy if exists "tg_groups_admin_update" on public.tg_groups;
drop policy if exists "tg_groups_admin_delete" on public.tg_groups;

drop policy if exists "tg_group_requests_admin_select" on public.tg_group_requests;
drop policy if exists "tg_group_requests_admin_insert" on public.tg_group_requests;
drop policy if exists "tg_group_requests_admin_update" on public.tg_group_requests;
drop policy if exists "tg_group_requests_admin_delete" on public.tg_group_requests;

drop policy if exists "tg_occurrences_admin_select" on public.tg_occurrences;


create table if not exists public.tg_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tg_telegram_status (
  user_id uuid primary key references auth.users(id) on delete cascade,
  status text not null default 'not_configured',
  phone_hint text,
  last_error text,
  updated_at timestamptz not null default now()
);

create table if not exists public.tg_telegram_private (
  user_id uuid primary key references auth.users(id) on delete cascade,
  api_id bigint not null,
  api_hash_enc text not null,
  phone_enc text not null,
  pending_session_enc text,
  session_enc text,
  phone_code_hash_enc text,
  updated_at timestamptz not null default now()
);

create table if not exists public.tg_coupon_sites (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  store_name text not null,
  store_slug text not null,
  sources text[] not null default array['meliuz','cuponeria']::text[],
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tg_coupons (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  coupon_key text not null,
  source text not null,
  store_name text not null default '',
  title text not null default '',
  code text,
  discount_text text,
  details text,
  source_url text,
  source_group text,
  active boolean not null default true,
  discovered_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  expires_at timestamptz,
  unique(user_id, coupon_key)
);

alter table public.tg_keywords
  add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.tg_group_requests
  add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.tg_occurrences
  add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.tg_occurrences
  add column if not exists is_coupon boolean not null default false;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='tg_groups' and column_name='id'
  ) and not exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='tg_groups' and column_name='telegram_group_id'
  ) then
    alter table public.tg_groups rename column id to telegram_group_id;
  end if;
end $$;

alter table public.tg_groups
  add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.tg_groups
  add column if not exists id bigint generated by default as identity;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='tg_occurrences' and column_name='group_id'
  ) and not exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='tg_occurrences' and column_name='telegram_group_id'
  ) then
    alter table public.tg_occurrences rename column group_id to telegram_group_id;
  end if;
end $$;

update public.tg_keywords set user_id='REPLACE_WITH_OWNER_4e162ad5-7770-4507-9759-622825ab4e80'::uuid where user_id is null;
update public.tg_groups set user_id='REPLACE_WITH_OWNER_4e162ad5-7770-4507-9759-622825ab4e80'::uuid where user_id is null;
update public.tg_group_requests set user_id='REPLACE_WITH_OWNER_4e162ad5-7770-4507-9759-622825ab4e80'::uuid where user_id is null;
update public.tg_occurrences set user_id='REPLACE_WITH_OWNER_4e162ad5-7770-4507-9759-622825ab4e80'::uuid where user_id is null;

alter table public.tg_keywords alter column user_id set not null;
alter table public.tg_groups alter column user_id set not null;
alter table public.tg_group_requests alter column user_id set not null;
alter table public.tg_occurrences alter column user_id set not null;

alter table public.tg_keywords alter column user_id set default auth.uid();
alter table public.tg_groups alter column user_id set default auth.uid();
alter table public.tg_group_requests alter column user_id set default auth.uid();

alter table public.tg_groups drop constraint if exists tg_groups_pkey;
alter table public.tg_groups add constraint tg_groups_pkey primary key (id);

drop index if exists public.tg_keywords_word_ci_uq;
create unique index if not exists tg_keywords_user_word_ci_uq
  on public.tg_keywords(user_id, lower(btrim(word)));

drop index if exists public.tg_occurrences_message_uq;
create unique index if not exists tg_occurrences_message_uq
  on public.tg_occurrences(user_id, telegram_group_id, message_id, keyword);

create unique index if not exists tg_groups_user_tgid_uq
  on public.tg_groups(user_id, telegram_group_id);

drop table if exists public.tg_worker_status cascade;
create table public.tg_worker_status (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state text not null default 'offline',
  last_heartbeat timestamptz,
  groups_active integer not null default 0,
  keywords_active integer not null default 0,
  last_error text,
  version text,
  updated_at timestamptz not null default now()
);

insert into public.tg_worker_status(user_id,state)
values ('REPLACE_WITH_OWNER_UUID'::uuid,'offline')
on conflict do nothing;

insert into public.tg_profiles(user_id)
values ('REPLACE_WITH_OWNER_UUID'::uuid)
on conflict do nothing;

insert into public.tg_telegram_status(user_id,status)
values ('REPLACE_WITH_OWNER_UUID'::uuid,'not_configured')
on conflict do nothing;

commit;

-- Depois, execute sql/fresh_install.sql para completar
-- triggers, RLS, grants, cron e funções da V2.
